### ISSUE TITLE
マウスのドラック&ドロップによる編集 

### ISSUE THREAD

**Issue by yukako** [tohsato-lab/bdmleditor#15]

**Comment by get-me-power** [comment]
とりあえず2Dでできるように頑張ってみます

3Dの場合は #20 とかを達成しないといけないので難易度が高いです

**Comment by get-me-power** [comment]
参考文献

https://qiita.com/SatoshiTerasaki/items/e216f7d0fad9ad39fc77

この参考文献で遊んで、全体像を掴みます（まだ見えていない)

**Comment by get-me-power** [comment]
on_pickedとon_motionを組み合わせることで実現できそうです。
（かなりコードを書き直さないといけない）
そのため、慎重に行っていきたいと思います

**Comment by get-me-power** [comment]
done
